language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - node_modules/
    - dist/

install:
  - npm install
script:
  - npm run build

branches:
  only:
    - master

deploy:
  - provider: surge
    skip_cleanup: true
    on:
      branch: master
      all_branches: true
    project: ./dist
    domain: https://filipveportfolio.surge.sh/
